2025-04-09 16:16:35,144 INFO    StreamThr :3613517 [internal.py:wandb_internal():86] W&B internal server running at pid: 3613517, started at: 2025-04-09 16:16:35.144071
2025-04-09 16:16:35,145 DEBUG   HandlerThread:3613517 [handler.py:handle_request():146] handle_request: status
2025-04-09 16:16:35,148 INFO    WriterThread:3613517 [datastore.py:open_for_write():85] open: /home/ghazal/Documents/NS_Projects/NS_Revised_P1/neural_decoding/outputs/logs/multirun/2025-04-09_16-10-27/10/wandb/run-20250409_161635-gdgzah9l/run-gdgzah9l.wandb
2025-04-09 16:16:35,148 DEBUG   SenderThread:3613517 [sender.py:send():380] send: header
2025-04-09 16:16:35,151 DEBUG   SenderThread:3613517 [sender.py:send():380] send: run
2025-04-09 16:16:35,465 DEBUG   HandlerThread:3613517 [handler.py:handle_request():146] handle_request: status_report
2025-04-09 16:16:35,569 ERROR   SenderThread:3613517 [internal_api.py:execute():369] 403 response executing GraphQL.
2025-04-09 16:16:35,569 ERROR   SenderThread:3613517 [internal_api.py:execute():370] {"errors":[{"message":"permission denied","path":["upsertBucket"],"extensions":{"code":"PERMISSION_ERROR"}}],"data":{"upsertBucket":null}}
2025-04-09 16:16:35,569 ERROR   SenderThread:3613517 [sender.py:send_run():977] It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 403: Forbidden)
Traceback (most recent call last):
  File "/home/ghazal/anaconda3/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/ghazal/anaconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 366, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/home/ghazal/anaconda3/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/ghazal/anaconda3/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/ghazal/anaconda3/lib/python3.10/site-packages/wandb/sdk/lib/gql_request.py", line 59, in execute
    request.raise_for_status()
  File "/home/ghazal/anaconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ghazal/anaconda3/lib/python3.10/site-packages/wandb/sdk/internal/sender.py", line 975, in send_run
    self._init_run(run, config_value_dict)
  File "/home/ghazal/anaconda3/lib/python3.10/site-packages/wandb/sdk/internal/sender.py", line 1013, in _init_run
    server_run, inserted, server_messages = self._api.upsert_run(
  File "/home/ghazal/anaconda3/lib/python3.10/site-packages/wandb/apis/normalize.py", line 73, in wrapper
    raise err
  File "/home/ghazal/anaconda3/lib/python3.10/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/ghazal/anaconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2007, in upsert_run
    response = self.gql(
  File "/home/ghazal/anaconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 338, in gql
    ret = self._retry_gql(
  File "/home/ghazal/anaconda3/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 147, in __call__
    retry_timedelta_triggered = check_retry_fn(e)
  File "/home/ghazal/anaconda3/lib/python3.10/site-packages/wandb/util.py", line 964, in check_retry_fn
    return fallback_retry_fn(e)
  File "/home/ghazal/anaconda3/lib/python3.10/site-packages/wandb/util.py", line 906, in no_retry_auth
    raise CommError(
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 403: Forbidden)
2025-04-09 16:16:36,011 DEBUG   HandlerThread:3613517 [handler.py:handle_request():146] handle_request: status_report
2025-04-09 16:16:36,452 DEBUG   HandlerThread:3613517 [handler.py:handle_request():146] handle_request: status_report
2025-04-09 16:16:36,881 DEBUG   HandlerThread:3613517 [handler.py:handle_request():146] handle_request: status_report
2025-04-09 16:16:37,541 DEBUG   HandlerThread:3613517 [handler.py:handle_request():146] handle_request: status_report
2025-04-09 16:16:37,886 DEBUG   HandlerThread:3613517 [handler.py:handle_request():146] handle_request: status_report
2025-04-09 16:16:38,310 DEBUG   HandlerThread:3613517 [handler.py:handle_request():146] handle_request: status_report
2025-04-09 16:16:38,816 DEBUG   HandlerThread:3613517 [handler.py:handle_request():146] handle_request: status_report
2025-04-09 16:16:39,083 DEBUG   HandlerThread:3613517 [handler.py:handle_request():146] handle_request: status_report
2025-04-09 16:16:39,576 DEBUG   HandlerThread:3613517 [handler.py:handle_request():146] handle_request: status_report
2025-04-09 16:16:40,152 DEBUG   HandlerThread:3613517 [handler.py:handle_request():146] handle_request: keepalive
2025-04-09 16:16:40,466 DEBUG   HandlerThread:3613517 [handler.py:handle_request():146] handle_request: status_report
2025-04-09 16:16:40,570 DEBUG   HandlerThread:3613517 [handler.py:handle_request():146] handle_request: status_report
2025-04-09 16:16:41,011 DEBUG   HandlerThread:3613517 [handler.py:handle_request():146] handle_request: status_report
2025-04-09 16:16:41,453 DEBUG   HandlerThread:3613517 [handler.py:handle_request():146] handle_request: status_report
2025-04-09 16:16:41,882 DEBUG   HandlerThread:3613517 [handler.py:handle_request():146] handle_request: status_report
2025-04-09 16:16:42,542 DEBUG   HandlerThread:3613517 [handler.py:handle_request():146] handle_request: status_report
2025-04-09 16:16:42,887 DEBUG   HandlerThread:3613517 [handler.py:handle_request():146] handle_request: status_report
2025-04-09 16:16:43,311 DEBUG   HandlerThread:3613517 [handler.py:handle_request():146] handle_request: status_report
2025-04-09 16:16:43,816 DEBUG   HandlerThread:3613517 [handler.py:handle_request():146] handle_request: status_report
2025-04-09 16:16:44,084 DEBUG   HandlerThread:3613517 [handler.py:handle_request():146] handle_request: status_report
2025-04-09 16:16:44,576 DEBUG   HandlerThread:3613517 [handler.py:handle_request():146] handle_request: status_report
2025-04-09 16:16:45,153 DEBUG   HandlerThread:3613517 [handler.py:handle_request():146] handle_request: keepalive
2025-04-09 16:16:45,466 DEBUG   HandlerThread:3613517 [handler.py:handle_request():146] handle_request: status_report
2025-04-09 16:16:45,571 DEBUG   HandlerThread:3613517 [handler.py:handle_request():146] handle_request: status_report
2025-04-09 16:16:46,012 DEBUG   HandlerThread:3613517 [handler.py:handle_request():146] handle_request: status_report
2025-04-09 16:16:46,453 DEBUG   HandlerThread:3613517 [handler.py:handle_request():146] handle_request: status_report
2025-04-09 16:16:46,882 DEBUG   HandlerThread:3613517 [handler.py:handle_request():146] handle_request: status_report
2025-04-09 16:16:47,542 DEBUG   HandlerThread:3613517 [handler.py:handle_request():146] handle_request: status_report
2025-04-09 16:16:47,887 DEBUG   HandlerThread:3613517 [handler.py:handle_request():146] handle_request: status_report
2025-04-09 16:16:48,312 DEBUG   HandlerThread:3613517 [handler.py:handle_request():146] handle_request: status_report
2025-04-09 16:16:48,817 DEBUG   HandlerThread:3613517 [handler.py:handle_request():146] handle_request: status_report
2025-04-09 16:16:49,084 DEBUG   HandlerThread:3613517 [handler.py:handle_request():146] handle_request: status_report
2025-04-09 16:16:49,577 DEBUG   HandlerThread:3613517 [handler.py:handle_request():146] handle_request: status_report
2025-04-09 16:16:50,154 DEBUG   HandlerThread:3613517 [handler.py:handle_request():146] handle_request: keepalive
2025-04-09 16:16:50,467 DEBUG   HandlerThread:3613517 [handler.py:handle_request():146] handle_request: status_report
2025-04-09 16:16:50,571 DEBUG   HandlerThread:3613517 [handler.py:handle_request():146] handle_request: status_report
2025-04-09 16:16:51,013 DEBUG   HandlerThread:3613517 [handler.py:handle_request():146] handle_request: status_report
2025-04-09 16:16:51,454 DEBUG   HandlerThread:3613517 [handler.py:handle_request():146] handle_request: status_report
2025-04-09 16:16:51,883 DEBUG   HandlerThread:3613517 [handler.py:handle_request():146] handle_request: status_report
2025-04-09 16:16:52,543 DEBUG   HandlerThread:3613517 [handler.py:handle_request():146] handle_request: status_report
2025-04-09 16:16:52,888 DEBUG   HandlerThread:3613517 [handler.py:handle_request():146] handle_request: status_report
2025-04-09 16:16:53,312 DEBUG   HandlerThread:3613517 [handler.py:handle_request():146] handle_request: status_report
2025-04-09 16:16:53,817 DEBUG   HandlerThread:3613517 [handler.py:handle_request():146] handle_request: status_report
2025-04-09 16:16:54,085 DEBUG   HandlerThread:3613517 [handler.py:handle_request():146] handle_request: status_report
2025-04-09 16:16:54,577 DEBUG   HandlerThread:3613517 [handler.py:handle_request():146] handle_request: status_report
2025-04-09 16:16:55,154 DEBUG   HandlerThread:3613517 [handler.py:handle_request():146] handle_request: keepalive
2025-04-09 16:16:55,467 DEBUG   HandlerThread:3613517 [handler.py:handle_request():146] handle_request: status_report
2025-04-09 16:16:55,572 DEBUG   HandlerThread:3613517 [handler.py:handle_request():146] handle_request: status_report
2025-04-09 16:16:56,013 DEBUG   HandlerThread:3613517 [handler.py:handle_request():146] handle_request: status_report
2025-04-09 16:16:56,454 DEBUG   HandlerThread:3613517 [handler.py:handle_request():146] handle_request: status_report
2025-04-09 16:16:56,883 DEBUG   HandlerThread:3613517 [handler.py:handle_request():146] handle_request: status_report
2025-04-09 16:16:57,543 DEBUG   HandlerThread:3613517 [handler.py:handle_request():146] handle_request: status_report
2025-04-09 16:16:57,888 DEBUG   HandlerThread:3613517 [handler.py:handle_request():146] handle_request: status_report
2025-04-09 16:16:58,313 DEBUG   HandlerThread:3613517 [handler.py:handle_request():146] handle_request: status_report
2025-04-09 16:16:58,818 DEBUG   HandlerThread:3613517 [handler.py:handle_request():146] handle_request: status_report
2025-04-09 16:16:59,085 DEBUG   HandlerThread:3613517 [handler.py:handle_request():146] handle_request: status_report
2025-04-09 16:16:59,578 DEBUG   HandlerThread:3613517 [handler.py:handle_request():146] handle_request: status_report
2025-04-09 16:17:00,155 DEBUG   HandlerThread:3613517 [handler.py:handle_request():146] handle_request: keepalive
2025-04-09 16:17:00,468 DEBUG   HandlerThread:3613517 [handler.py:handle_request():146] handle_request: status_report
2025-04-09 16:17:00,513 DEBUG   HandlerThread:3613517 [handler.py:handle_request():146] handle_request: shutdown
2025-04-09 16:17:00,513 INFO    HandlerThread:3613517 [handler.py:finish():866] shutting down handler
2025-04-09 16:17:00,572 DEBUG   HandlerThread:3613517 [handler.py:handle_request():146] handle_request: status_report
2025-04-09 16:17:01,014 DEBUG   HandlerThread:3613517 [handler.py:handle_request():146] handle_request: status_report
2025-04-09 16:17:01,455 DEBUG   HandlerThread:3613517 [handler.py:handle_request():146] handle_request: status_report
2025-04-09 16:17:01,468 INFO    SenderThread:3613517 [sender.py:finish():1534] shutting down sender
2025-04-09 16:17:01,469 INFO    WriterThread:3613517 [datastore.py:close():294] close: /home/ghazal/Documents/NS_Projects/NS_Revised_P1/neural_decoding/outputs/logs/multirun/2025-04-09_16-10-27/0/wandb/run-20250409_161030-tj9k6r3d/run-tj9k6r3d.wandb
